name: foos-db-app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: foos-db-app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure rust nightly
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: nightly
        target: wasm32-unknown-unknown
        default: true
    - name: Install trunk
      uses: jetli/trunk-action@v0.1.0
    - name: Build
      run: trunk build --release
    - name: Create 200.html
      working-directory: foos-db-app/dist
      run: cp index.html 200.html
  deploy:
    runs-on: ubuntu-latest
    needs: build
    #if: github.ref == 'refs/heads/main'
    steps:
      - name: find
        run: find
      - name: Publish to foos-db-cn
        uses: dswistowski/surge-sh-action@v1.0.1
        with:
          domain: http://foos-db-cn.ericchu.net
          # surge.sh login
          login: ericchu137@live.ca
          token: ${{ secrets.SURGE_TOKEN }}
          project: foos-db-app/dist
      - name: Publish to foos-db
        uses: dswistowski/surge-sh-action@v1.0.1
        with:
          domain: http://foos-db.ericchu.net
          # surge.sh login
          login: ericchu137@live.ca
          token: ${{ secrets.SURGE_TOKEN }}
          project: foos-db-app/dist
